# Site settings
title: skynet club
email: forthxu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  skynet是云风编写的服务端底层管理框架，底层由C编写，配套lua作为脚本使用，可换python等其他脚本语言。skynet主要工作是管理注册服务，并开启多线程协调服务之间的调用和通讯。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skynetclub.forthxu.com" # the base hostname & protocol for your site
permalink: /:categories/:title.html
#twitter_username: forthxu
github_username:  skynetclub

host: 0.0.0.0

# Build settings
markdown: kramdown
